### ISSUE TITLE
List of Books

### ISSUE THREAD

**Issue by ArnelaKapllani** [ArnelaKapllani/capstone-arnela#1]
## Value proposition

As an user
I want to have a list of all books
So that I can see which books are available for purchase 

## Description

<img width="232" alt="Screenshot 2023-07-06 at 12 14 48" src="https://github.com/ArnelaKapllani/capstone-arnela/assets/130066692/36e54b95-2df2-434a-addc-3fa991fb1b04">

## Acceptance criteria

- [ ] A headline "List of books" should be displayed.
- [ ] All books with covers should be displayed as a vertical list.

## Tasks

- [ ] Connect the database to the application to retrieve the data.
- [ ] Create a Book component and define the structure and layout of a book.
- [ ] Create a BooksList component and define an array of books using .map().
- [ ] Render the Book component for each book within the BooksList component.
- [ ] In the App.js import the BooksList component and render it.
- [ ] Style the list of books.

**Comment by vaupunkt** [comment]
Looks good. maybe in your wireframe you can show only what you want to code. so in this US for example you don't have an navigation bar yet, so maybe you would only display your book list. in later userstories you can display the full layout when you then have the navigation.

So after coding this US, your app should look like this: 

![Image](https://github.com/ArnelaKapllani/capstone-arnela/assets/119793693/66e8bc9a-29cf-4879-9303-ee3b8c8fd55a)
