### ISSUE TITLE
Add the book the shopping cart

### ISSUE THREAD

**Issue by ArnelaKapllani** [ArnelaKapllani/capstone-arnela#10]
## Value proposition

As an user
I want to click the shopping cart button 
So that I can put the desired book in the shopping cart

## Description 

![Image](https://user-images.githubusercontent.com/130066692/252925047-04330813-7bf3-47cd-ae44-89a3df4e6f54.png)

## Acceptance criteria

- [ ] A heading "My cart" should displayed.
- [ ] The book cover should be displayed.
- [ ] A drop-down button should be displayed.
- [ ] A delete button should be displayed.
- [ ] A bookmark button should be displayed.
- [ ] The total price should be displayed.
- [ ] A button "Next" should be displayed.

## Tasks

- [ ] Create a new page My cart.
- [ ] Display on this page the image of the searched book.
- [ ] Create a DeleteButton component.
- [ ] Create a BookmarkButton component.
- [ ] Create a NextButton component.
- [ ] Create a dropdown button to choose how many books to buy.
- [ ] Create a function to calculate the total price depending on the quantity you will buy.

**Comment by DErdmann1** [comment]
LGTM :) A lot of component-work 😅
