### ISSUE TITLE
Application header

### ISSUE THREAD

**Issue by ArnelaKapllani** [ArnelaKapllani/capstone-arnela#12]
## Value proposition

As an user
I want to have an app name
So i can see what the app is called
 
## Description

![Image](https://user-images.githubusercontent.com/130066692/253284357-a9a54bf3-2fe9-4d81-bfee-cc21eb2e29f7.png)

## Acceptance criteria

- [ ] A header with the app name should be displayed.

## Tasks

- [ ] Create Header component.
- [ ] Style it. 
- [ ] Apply the footer component in pages/_app.
