### ISSUE TITLE
Dark mode option

### ISSUE THREAD

**Issue by ArnelaKapllani** [ArnelaKapllani/capstone-arnela#13]
## Value proposition

As a user
I want to have a dark mode button
So I can switch between dark and light mode

## Description

![Image](https://user-images.githubusercontent.com/130066692/253285180-d2dd758c-b70d-4d08-a74e-572588d882e7.png)

## Acceptance criteria

- [ ] A dark mode button on the header should be displayed.

## Tasks

- [ ] Create component toggle button.
- [ ] Pass it to the Header component.
- [ ] Style it.
