### ISSUE TITLE
Add and manipulate the book in the shopping cart

### ISSUE THREAD

**Issue by ArnelaKapllani** [ArnelaKapllani/capstone-arnela#15]
## Value proposition

As a user
I want to add the book to the shopping cart
So that I can continue with the purchase

## Description 

![Image](https://github.com/ArnelaKapllani/capstone-arnela/assets/130066692/0cf0a431-6118-401f-a706-77e25c5f19f6)

## Acceptance criteria

- [ ] By clicking on the Shopping Cart Button in the search page, the book should be displayed on the shopping cart page.
- [ ] A heading "My Cart" should be displayed.
- [ ] The book should be displayed.
- [ ] A dropdown button, to choose the amount of books, should be displayed.
- [ ] A delete button should be displayed.
- [ ] A bookmark button should be displayed.
- [ ] The total price should be displayed.
- [ ] A "Next" button should be displayed.

## Tasks

- [ ] Create a new page shopping-cart.
- [ ] Modify the ShoppingCartButton component so that when i click on it, the selected book "goes" to the shopping cart page.
- [ ] Create DeleteButton Component.
- [ ] Create DropdownButton Component.
- [ ] Create NextButton Component.
- [ ] Apply BookmarkButton Component created on the previous page.
- [ ] Create a function to calculate the total price.

**Comment by JivanaLipsewers** [comment]
lgtm! :)
