### ISSUE TITLE
Delete function

### ISSUE THREAD

**Issue by ArnelaKapllani** [ArnelaKapllani/capstone-arnela#16]
## Value proposition

As a user
I want to click on the delete button
So that I can delete a book from the shopping cart

## Description

![Image](https://user-images.githubusercontent.com/130066692/253526926-466efa01-dbb1-4d36-a8e5-e63f98127fb1.png)

## Acceptance criteria

- [ ] A delete button below the book should be displayed.

## Tasks

- [ ] Modify the DeleteButton component to add the delete function.
- [ ] Modify the DeleteButton component so that after clicking the delete button the book disappears from the page.

**Comment by JivanaLipsewers** [comment]
Looks good! :)
