### ISSUE TITLE
"My list" page of bookmarked books

### ISSUE THREAD

**Issue by ArnelaKapllani** [ArnelaKapllani/capstone-arnela#18]
## Value proposition

As a user
I want to have a page 
So that I can have all my bookmarked books

## Description

![Image](https://user-images.githubusercontent.com/130066692/253539061-00f6d916-72b0-49d5-8c68-f9d81ee12c2c.png)

## Acceptance criteria

- [ ] A heading "My list" should be displayed.
- [ ] The bookmarked book should be displayed.
- [ ] The bookmark button should be displayed.

## Tasks 

- [ ] Create a page "my list".
- [ ] Apply the BookmarkButton component, so when this button is clicked, the book is removed from the bookmark list.
- [ ] Make the book clickable so when the book is clicked, the description page should be displayed.

**Comment by DErdmann1** [comment]
Hi Arnela 😄  I like your US! Maybe u could a Acceptance criteria like.. "the bookmark should change the color if i add the icon to my favorites". Not necessary.
