### ISSUE TITLE
User Story 2 - Search Bar

### ISSUE THREAD

**Issue by ArnelaKapllani** [ArnelaKapllani/capstone-arnela#2]
## Value proposition

As an user
I want to have a search bar
So that I can search easily for the book I want and proceed with the two options: "buy" and/or "bookmark" 

## Description

![Image](https://user-images.githubusercontent.com/130066692/251424837-7766580a-0e5e-480a-94c8-ae5ceedcb37c.png)

## Acceptance criteria

- [ ] An input field and a search button should be displayed.
- [ ] The searched book should be listed together with the price.
- [ ] The shopping cart and bookmark buttons should be displayed.

## Tasks

- [ ] Create a SearchInput component and define a state variable to store the search query value.
- [ ] In the BooksList component, modify the rendering logic to filter the list of books based on the search query.
- [ ] Define a new state variable to store the filtered list of books.
- [ ] Create a function on BooksList that takes the search query as input and filters the original list of book.
- [ ] Use array method .filter() to match the search query against the book title or other relevant fields.
- [ ] Style the elements.

**Comment by vaupunkt** [comment]
looks very good! 
Is in the filtered list only the book cover or are you going to display also for example the name of the book? :)

**Comment by ArnelaKapllani** [comment]
This (the book Details) will come to another page and therefore to another user story, for which I am working right now 🏃‍♀️ 🙂
But, the title and the author will be on the cover.
