### ISSUE TITLE
The successful message

### ISSUE THREAD

**Issue by ArnelaKapllani** [ArnelaKapllani/capstone-arnela#20]
## Value proposition

As a user
I have to click on the Buy button
So that I can complete my purchase

## Description

![Image](https://user-images.githubusercontent.com/130066692/253555429-6f4e46c2-833c-420b-b6c2-cfec4e359841.png)

## Acceptance criteria

- [ ] A modal page should be displayed.
- [ ] A successful message should be displayed.
- [ ] A close button should be displayed.

## Tasks

- [ ] Create a modal page.
- [ ] Modify the BuyButton component so clicking on it should display the modal page.
- [ ] Create a CloseButton component.
