### ISSUE TITLE
User Story 3 - Details Page

### ISSUE THREAD

**Issue by ArnelaKapllani** [ArnelaKapllani/capstone-arnela#3]
## Value proposition

As an user
I want to click on each book 
So that I can see the details of the clicked book

## Description

![Image](https://user-images.githubusercontent.com/130066692/251467564-027bf486-8361-4219-b343-be27b51815dc.png)

## Acceptance criteria

- [ ] The clicked book should be displayed.
- [ ] The product details should be displayed.
- [ ] The book description should be displayed.
- [ ] A cancel button should be displayed to close the details page.

## Tasks

- [ ] Create a BookDetails component.
- [ ] Fetch the details of a specific book based on the id parameter.
- [ ] Create a link for each book in the book list to navigate to the book details page using Link component.
- [ ] Create a button to close the details page and to navigate back to the book list. 
- [ ] Style the components.
